# Generated by Django 4.1.1 on 2022-09-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='club',
            name='info',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
