# Generated by Django 4.1.1 on 2022-09-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_country_club_image_club_info_alter_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
    ]
