# Generated by Django 4.1.1 on 2022-09-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='club',
            name='image_2',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='club',
            name='image_3',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='club',
            name='stadium',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='club',
            name='stadium_capacity',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
