# Generated by Django 4.1.1 on 2022-09-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('position', models.CharField(default=None, max_length=50)),
                ('nationality', models.CharField(default=None, max_length=50)),
                ('info', models.TextField(blank=True, default=None, max_length=500)),
                ('goals', models.PositiveIntegerField(default=None)),
                ('international_caps', models.PositiveIntegerField(default=None)),
                ('shirt_number', models.PositiveIntegerField(default=None)),
                ('image_1', models.CharField(default=None, max_length=300)),
                ('image_2', models.CharField(default=None, max_length=300)),
                ('image_3', models.CharField(default=None, max_length=300)),
                ('clubs', models.ManyToManyField(related_name='players', to='clubs.club')),
            ],
        ),
    ]
