# Generated by Django 4.1.1 on 2022-09-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('position', models.CharField(default=None, max_length=50)),
                ('nationality', models.CharField(default=None, max_length=50)),
                ('info', models.CharField(default=None, max_length=500)),
                ('goals', models.PositiveIntegerField(default=None)),
                ('shirt_number', models.PositiveIntegerField(default=None)),
                ('image', models.ImageField(default=None, upload_to='images')),
            ],
        ),
    ]
