# Generated by Django 4.1.1 on 2022-09-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='player',
            name='info',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
