# Generated by Django 4.1.1 on 2022-09-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_image_alter_player_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='international_caps',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='info',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
