# Generated by Django 4.1.1 on 2022-09-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0003_player_international_caps_alter_player_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clubs',
            field=models.ManyToManyField(related_name='players', to='clubs.club'),
        ),
    ]
